#+TITLE: nbodybox

Playground for working with WebGL, Node-Webkit and ClojureScript.

Under construction.  Hard hats required.  Pointy bits everywhere.  Use
at your own risk.  YMMV.  Do not try this at home.  Professional
driver, closed course.  Consumption of =nbodybox= may cause hives,
itching, dizzyness and spelling errors.

* Things that work:
** Create node-webkit project
- Adapt Brett Lischalk's [[https://github.com/blischalk/cljs-node-webkit-app/][work-in-progress]] ([[https://github.com/blischalk/cljs-node-webkit-app/blob/master/project.clj][project.clj]] and other files).
- Use [[https://github.com/wilkerlucio/lein-node-webkit-build][this project]] to build (=lein node-webkit-build=).
- Workflow (using [[https://github.com/eigenhombre/continuous-testing-helper][conttest]]):

#+BEGIN_EXAMPLE
    conttest ' \
      touch src/cljs/nbodybox/core.cljs && \
      lein cljsbuild once               && \
      lein node-webkit-build            && \
      unzip -o releases/NBodyBox-v0.0.0/NBodyBox-osx64-v0.0.0.zip && \
      open NBodyBox.app'
#+END_EXAMPLE

This will cause the app to be rebuilt every time you save a file in
the directory.  Unfortunately the whole thing takes several seconds; I
would like to find a workflow which is a bit more interactive, but
haven't figured out how to get a working ClojureScript REPL *plus* a
Node Webkit build working in the same project yet.

** Create cool icon

Directions:
- make square PNG image any way you care to.
- Use [[http://iconverticons.com/online/]] and save =.icns= file to
  =resources/icons/myicon.icns=.
- Add =:osx { :icon "resources/icons/myicon.icns"}= to
  =:node-webkit-build= map in =project.clj=.

** Create cool splash screen
(Splash screens can be lame, I know, but it's my project, dammit.)

See [[https://github.com/rogerwang/node-webkit/issues/811]].  Currently
the first window started is the main screen.  It will need to create
the "main" app window when it closes.

* Next Steps:

Make the simplest possible WebGL rendering.

* Disclaimer

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
